[package]
name = "titration-curve"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
calamine = "0.23.1"
iced = { git = "https://github.com/iced-rs/iced.git", version = "0.12.0", features = ["smol", "svg"] }
notify = "6.1.1"
rfd = "0.12.1"
svg = "0.14.0"
